version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /home/ubuntu/redis/data:/data
      - /home/ubuntu/redis/conf/redis.conf:/usr/local/conf/redis.conf
    command: /bin/sh -c "mkdir -p /usr/local/conf && redis-server /usr/local/conf/redis.conf"
    networks:
      - golaping-network
  spring-app:
    image: joonghyunkim/golaping:latest
    container_name: golaping-container
    environment:
      - SPRING_REDIS_HOST=redis-container
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - golaping-network
networks:
  golaping-network:
    driver: bridge
