name: CI Workflow

on:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Install JDK 
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21' 
          distribution: 'temurin'

      # Create application file
      - name: Create application.yml
        run: |
          mkdir ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_FILE }}" > ./application.yml
        shell: bash

      # Grant permission
      - name: Grant permission for gradlew
        run: chmod +x gradlew

      # Gradle build and test
      - name: Build and test with Gradle
        run: ./gradlew build 

      # Show test result as PR comment
      - name: Publish test results as PR comment
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() 
        with:
          files: '**/build/test-results/test/TEST-*.xml'
        
      # Add check comment for failed test cases
      - name: Add check comment for failed test cases
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      # Docker Hub login
      - name: Docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/golaping .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/golaping
